### ISSUE TITLE
Tedge build error-chart.js

### ISSUE THREAD

**Issue by yucelzengin** [thin-edge/thin-edge.io_examples#27]
chart.js package is missing in the package.json and causes a build error problem._ 

Error: node_modules/chartjs-plugin-streaming/types/index.d.ts:1:87 - error TS2307: Cannot find module 'chart.js' or its corresponding type declarations.

1 import { Chart, ChartComponent, ChartType, TimeScale, TimeScaleOptions, Plugin } from 'chart.js';
                                                                                        ~~~~~~~~~~
node_modules/ng2-charts/lib/base-chart.directive.d.ts:2:84 - error TS2307: Cannot find module 'chart.js' or its corresponding type declarations.

2 import { Chart, ChartConfiguration, ChartEvent, ChartType, DefaultDataPoint } from 'chart.js';
                                                                                     ~~~~~~~~~~
node_modules/ng2-charts/lib/ng-charts.module.d.ts:2:56 - error TS2307: Cannot find module 'chart.js' or its corresponding type declarations.

2 import { ChartComponentLike, ChartConfiguration } from 'chart.js';
                                                         ~~~~~~~~~~
node_modules/ng2-charts/lib/theme.service.d.ts:2:50 - error TS2307: Cannot find module 'chart.js' or its corresponding type declarations.

2 import { ChartConfiguration, ChartOptions } from 'chart.js';
                                                   ~~~~~~~~~~
src/app/analysis/charting-widget.component.ts:3:69 - error TS2307: Cannot find module 'chart.js' or its corresponding type declarations.

3 import { Chart, ChartOptions, ChartConfiguration, UpdateMode } from 'chart.js';
                                                                      ~~~~~~~~~~

**Comment by sagIoTPower** [comment]
Hi @yucelzengin,
could you pls. try again. I tested the build again and it works for me.

Regards Christof
