### ISSUE TITLE
ERROR: Service 'tedge' depends on service 'tedge_build' which is undefined.

### ISSUE THREAD

**Issue by yucelzengin** [thin-edge/thin-edge.io_examples#28]
could you please write a brief comment or explanation about the build order and details?

**Comment by sagIoTPower** [comment]
@yucelzengin : Could you pls. try again to build the docker imaghe. The service "tedge_build" was removed as a multistage build in the ../thin-edge.io_examples/management-ui/tedge/Dockerfile was used?

**Comment by reubenmiller** [comment]
Closing due to lack of response. Please reopen if your problem still persists.
