### ISSUE TITLE
ERROR: Service 'tedge' failed to build : Build failed

### ISSUE THREAD

**Issue by yucelzengin** [thin-edge/thin-edge.io_examples#29]
This is the error details:
> [stage-1 70/73] RUN ng build  --output-path=/app/tedge/dist/cumulocity-tedge-setup:
#83 18.24 (node:1) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /app/tedge/node_modules/postcss/package.json.
#83 18.24 Update this package.json to use a subpath pattern like "./*".
#83 18.24 (Use `node --trace-deprecation ...` to show where the warning was created)
#83 49.29 - Generating ES5 bundles for differential loading...
#83 151.9 An unhandled exception occurred: Call retries were exceeded
#83 151.9 See "/tmp/ng-mGnBiG/angular-errors.log" for further details.
------
executor failed running [/bin/sh -c ng build  --output-path=/app/tedge/dist/cumulocity-tedge-setup]: exit code: 127
ERROR: Service 'tedge' failed to build : Build failed
--------
As a solution: the docker memory config must be set greater than 2GB, 4GB is stable and working.

**Comment by sagIoTPower** [comment]
Added comment to increase docker memory
