### ISSUE TITLE
ThinEdge can't connect to tenant

### ISSUE THREAD

**Issue by smeus** [thin-edge/thin-edge.io_examples#31]
We are using the example from https://github.com/thin-edge/thin-edge.io_examples/tree/main/opcua-solution.

- c8y.url is configured without any prefix (http/https)
- The certificate is created. 
- When trying to upload the certificate the following error is shown:

![grafik](https://user-images.githubusercontent.com/106586248/171135965-4152eff1-7898-4df6-a91c-b297c5095e10.png)

Two weeks before we could connect via ThinEdge to our tenant. At the moment it is not possible.

Thanks in advance for your support.

**Comment by smeus** [comment]
The versiob of the `thin-edge` is 0.6.1

**Comment by mbay-ODW** [comment]
I just double checked with the same version on adamos.com and adamos-dev.com with no issues. I have the feeling that there is something within the network not properly configured in terms of DNS. Can you describe your setup a bit more?

**Comment by smeus** [comment]
We modified the dockerfile to transfer the certificate, the key and the baseUrl via the `.env` file. Then via a shell script the certificate and key are copied in the respective folder. The script launches `tedge disconnect c8y` to disconnect any possible bridges to the c8y cloud, set the baseUrl via `tedge config set c8y.url ${baseUrl}` and finally connects to the cloud via `tedge connect c8y`. Everything else is the same except some additions to make running the shell script work via openRC in the dockerfile.

**Comment by albinsuresh** [comment]
Could you do an `nslookup ${baseUrl}` from inside that container to rule out any networking misconfiguration?

**Comment by mbay-ODW** [comment]
Did you rebuild the docker container after the 21st of May? I just saw that there was a jump in the base image version from 3.15 -> 3.16 about 10 days ago. The Dockerfile uses :latest tag.

**Comment by smeus** [comment]
@albinsuresh: the `nslookup` was ok. The IP was the same I got over a Windows ping.
@mbay-ODW: Yes, I already rolled the alpine version back because it was causing the `/sbin/init` Entrypoint to fail

I did some research myself and apparently we had a certificate problem, which caused this kind of behaviour. After generating new certificates the error message is gone.

**Comment by albinsuresh** [comment]
@smeus A corrupt certificate "appearing" as DNS lookup error is confusing and we'd like to improve that error reporting from thin-edge if possible. So, could you please share some details of that certificate issue?

**Comment by smeus** [comment]
@albinsuresh: At first we tried to get the connection working via our own certificate and private key file. This would lead to a `not authorized` error message. The key file was an encrypted private key, but the header and footer stated just `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----`. That was probably the issue. To check if the connection was working normally, we removed the certificate inside the container via `tedge cert remove` and then generated ( `tedge cert create` ) a new one. When trying to upload the new test certificate the above mentioned error message was displayed.

**Comment by mbay-ODW** [comment]
@albinsuresh Customer found out that this was based on the fact that he encrypted the certificates via -sha256.
I guess this should be considered somewhere in the documentation that the certificate should not be encrypted. And of course some log message that indicates that something is wrong with the certificate.
