### ISSUE TITLE
The collectd.conf in the thin-edge.io repository doesn't work for Alpine

### ISSUE THREAD

**Issue by NeilCondon** [thin-edge/thin-edge.io_examples#37]
This issue is listed in the known issues for docker-alpine, but affects other examples using containerised thin/edge on apline.

I think the problem is that the apk package for collectd hasn't been built with mqtt support:  the collectd.conf is fine, its just that the collected data are never posted to thin/edge's mqtt broker.

The solution is to install the optional package 'apk add --no-cache collectd-mqtt' in the Dockerfile.

**Comment by reubenmiller** [comment]
Closing as the docker-alpine example has been removed in place of the standalone repository: https://github.com/thin-edge/tedge-demo-container
