### ISSUE TITLE
Error in building docker container from docker-alpine

### ISSUE THREAD

**Issue by LP-SwAG** [thin-edge/thin-edge.io_examples#47]
> [stage-1 18/33] RUN sudo -u tedge tedge_agent --init:
#28 0.518 2022-12-15T11:21:09.1317488Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge_agent.lock"
#28 0.518 2022-12-15T11:21:09.131788Z  INFO tedge_agent::agent: tedge_agent starting
#28 0.519 Error: Creating the directory failed: "/var/tedge/".

adding the following fixed it: (cfr. dockerfile from opcua-solution):
` # Create useful directories`
`RUN mkdir /var/tedge \`
`    && chown tedge:tedge /var/tedge `

**Comment by reubenmiller** [comment]
Closing as the docker-alpine example has been removed in place of the standalone repository: https://github.com/thin-edge/tedge-demo-container
